

database:
  username: root
  password: 123456
  port: 3306
  ip: 47.94.170.239
  dbName: bloom
  xx: LsWqU73!@#
  docker: docker run -it --name Tmysql  -p 3306:3306 -v /home/docker/mysql:/mydata/mysql/data -e MYSQL_ROOT_PASSWORD=123456 b05128b000dd


secret: 1231qwdqwd

aliyun:
  key : nnx0D0Y8L2Qm0gbChwnCvQxQjrLsg1
  id : LTAI5tJxFtfCZUTDD8XSFjL1
smtp:
  from: 1500676800@qq.com
  qq:
    host: smtp.qq.com
    port: 25             # SSL协议端口：465/994
    username: 1500676800
    password: oongfnnuwjnfhfgi          #这里是授权码