

database:
  username: root
  password: 123456
  port: 80
  ip: localhost
  dbName:
  xx: LsWqU73!@#
  docker: docker run -it --name Tmysql  -p 3306:3306 -v /home/docker/mysql:/mydata/mysql/data -e MYSQL_ROOT_PASSWORD=123456 b05128b000dd