

database:
  username: root
  password: 123456
  port: 80
  ip: localhost
  dbName:
  docker: docker run -p 3306:3306 -v F:\goSRC\src\turan.com\example-goWeb\web\database:/mydata/mysql/data -e MYSQL_ROOT_PASSWORD=123456 b05128b000dd