definitions:
  route.Code:
    properties:
      err:
        type: string
      statusCode:
        type: integer
    type: object
info:
  contact: {}
paths:
  /sendEmailCode:
    post:
      parameters:
      - description: 邮箱
        in: body
        name: email
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 请求错误
          schema:
            $ref: '#/definitions/route.Code'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/route.Code'
      summary: 发送手机验证码
swagger: "2.0"
